/* PILAR SoundScope v4.4.0 — shared sample engine */
(function(){'use strict';const A=window.SOUNDSCOPE_MORSE_AUDIO;if(!A)return;
class AcousticEngine{
 constructor(){this.ctx=null;this.node=null;this.sink=null;this.source=null;this.ready=false;this.loading=null;this.sr=48000;this.ring=new Float32Array(1<<18);this.mask=this.ring.length-1;this.last=0;this.first=0;this.listeners=new Set();this.osc=null;this.og=null}
 async ensure(){A.ensure();this.ctx=A.ctx;this.sr=this.ctx.sampleRate||48000;if(!A.micOn)await A.startMic();if(!A.micOn||!A.src)throw Error('Mikrofon belum aktif');if(this.ready&&this.source===A.src)return this;await this.detach(false);if(!this.loading)this.loading=this.ctx.audioWorklet.addModule('./acoustic-capture-worklet.js?v=4.4.0');await this.loading;this.node=new AudioWorkletNode(this.ctx,'pilar-acoustic-capture',{numberOfInputs:1,numberOfOutputs:1,outputChannelCount:[1]});this.sink=this.ctx.createGain();this.sink.gain.value=1;this.node.connect(this.sink);this.sink.connect(this.ctx.destination);A.src.connect(this.node);this.source=A.src;this.last=0;this.first=0;this.ring.fill(0);this.node.port.onmessage=e=>{const m=e.data;if(!m)return;if(m.type==='samples'&&m.data){const x=m.data,end=m.end,start=end-x.length;for(let i=0;i<x.length;i++)this.ring[(start+i)&this.mask]=x[i];this.last=end;this.first=Math.max(0,this.last-this.ring.length)}else for(const fn of this.listeners)try{fn(m)}catch(_){}};this.ready=true;return this}
 on(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn)}mark(){return this.last}
 slice(a,b){a=Math.max(this.first,Math.floor(a));b=Math.min(this.last,Math.floor(b));if(b<=a)return new Float32Array(0);const out=new Float32Array(b-a);for(let i=0;i<out.length;i++)out[i]=this.ring[(a+i)&this.mask];return out}
 recent(ms){return this.slice(this.last-Math.round(this.sr*ms/1000),this.last)}
 async playSamples(samples,amp=.28,leadMs=70){await this.ensure();const buf=this.ctx.createBuffer(1,samples.length,this.sr);buf.copyToChannel(samples,0);const src=this.ctx.createBufferSource(),g=this.ctx.createGain();g.gain.value=amp;src.buffer=buf;src.connect(g);g.connect(this.ctx.destination);const when=this.ctx.currentTime+leadMs/1000;src.start(when);return {source:src,when,leadMs}}
 async playToneBurst(freq,durMs=24,amp=.26,leadMs=75){A.ensure();this.ctx=A.ctx;const osc=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime+leadMs/1000,d=durMs/1000;osc.type='sine';osc.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(amp,t+.003);g.gain.setValueAtTime(amp,t+Math.max(.004,d-.004));g.gain.linearRampToValueAtTime(0,t+d);osc.connect(g);g.connect(this.ctx.destination);osc.start(t);osc.stop(t+d+.02);return {osc,g,when:t}}
 startTone(freq=2000,amp=.16){A.ensure();this.ctx=A.ctx;this.stopTone();this.osc=this.ctx.createOscillator();this.og=this.ctx.createGain();this.osc.type='sine';this.osc.frequency.value=freq;this.og.gain.value=0;this.osc.connect(this.og);this.og.connect(this.ctx.destination);this.osc.start();this.og.gain.setTargetAtTime(amp,this.ctx.currentTime,.03)}
 stopTone(){if(this.og&&this.ctx)try{this.og.gain.setTargetAtTime(0,this.ctx.currentTime,.02)}catch(_){}if(this.osc)try{this.osc.stop((this.ctx?.currentTime||0)+.08)}catch(_){}this.osc=null;this.og=null}
 async setResponder(config){await this.ensure();this.stopTone();this.node.port.postMessage({type:'responder',enabled:true,config})}stopResponder(){if(this.node)this.node.port.postMessage({type:'responder',enabled:false})}
 async detach(stopTone=true){this.stopResponder();if(stopTone)this.stopTone();if(this.source&&this.node){try{this.source.disconnect(this.node)}catch(_){}}if(this.node){try{this.node.disconnect()}catch(_){}}if(this.sink){try{this.sink.disconnect()}catch(_){}}this.node=null;this.sink=null;this.source=null;this.ready=false}
}
window.PilarAcousticEngine=new AcousticEngine();})();