/* PILAR SoundScope v4.5.2 — Acoustic Physics */
(function(){
'use strict';
const A=window.SOUNDSCOPE_MORSE_AUDIO,C=window.PilarAcousticCore,E=window.PilarAcousticEngine,$=id=>document.getElementById(id);
if(!A||!C||!E||!$('acousticControlMount')||!$('acousticStage'))return;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),sleep=ms=>new Promise(r=>setTimeout(r,ms));
function autoPerf(){
 const ua=(typeof navigator==='object'&&navigator.userAgent)||'',android=/Android/i.test(ua);
 const choice=(()=>{try{return localStorage.getItem('ss_acoustic_perf')||'auto'}catch(_){return 'auto'}})();
 const mode=choice==='full'||choice==='eco'?choice:(android?'eco':'full');
 return {choice,mode,analysisRate:mode==='full'?48000:24000,frameMs:mode==='full'?16:33,dprMax:mode==='full'?2:1.25,trailMax:mode==='full'?40:24,trailMs:mode==='full'?9000:6000,livePause:mode==='full'?160:320};
}
let PERF=autoPerf(),lastDraw=0,dspWorker=null,dspSeq=0,dspWait=new Map();
function ensureDspWorker(){
 if(dspWorker||typeof Worker!=='function')return dspWorker;
 try{
  dspWorker=new Worker('./acoustic-dsp-worker.js?v=4.5.1');
  dspWorker.onmessage=e=>{const m=e.data||{},p=dspWait.get(m.id);if(!p)return;dspWait.delete(m.id);m.ok?p.resolve(m.result):p.reject(Error(m.error||'DSP worker gagal'))};
  dspWorker.onerror=()=>{for(const p of dspWait.values())p.reject(Error('DSP worker error'));dspWait.clear();try{dspWorker.terminate()}catch(_){}dspWorker=null};
 }catch(_){dspWorker=null}
 return dspWorker;
}
function analyzeSonarAsync(samples,opt){
 const w=ensureDspWorker();
 if(!w){const chirp=C.makeChirp({sr:E.sr,durationMs:10,f0:2200,f1:7000,amp:.9});return Promise.resolve(C.analyzeEcho(samples,chirp,opt))}
 const id=++dspSeq;
 return new Promise((resolve,reject)=>{dspWait.set(id,{resolve,reject});w.postMessage({type:'sonar',id,samples,sr:E.sr,targetRate:PERF.analysisRate,chirp:{durationMs:10,f0:2200,f1:7000,amp:.9},opt},[samples.buffer])});
}
function perfLabel(){const b=$('apPerfBadge');if(b)b.textContent=(PERF.choice==='auto'?'AUTO→':'')+PERF.mode.toUpperCase()+' · DSP '+Math.round(PERF.analysisRate/1000)+'k · '+Math.round(1000/PERF.frameMs)+'fps'}
function setPerfChoice(v){try{localStorage.setItem('ss_acoustic_perf',v)}catch(_){}PERF=autoPerf();lastDraw=0;perfLabel();fit()}

const DEF=[{id:'A',x:0,y:0,poll:1000,reply:1800},{id:'B',x:6,y:0,poll:1200,reply:2000},{id:'C',x:6,y:4,poll:1400,reply:2200},{id:'D',x:0,y:4,poll:1600,reply:2400}];
let cached=null;try{cached=JSON.parse(localStorage.getItem('ss_acoustic_anchors_v1')||'null')}catch(_){}
const anchors=DEF.map((a,i)=>({...a,x:cached?.[i]?.x??a.x,y:cached?.[i]?.y??a.y,range:cached?.[i]?.range??null,bias:cached?.[i]?.bias??0,q:cached?.[i]?.q??0}));
const S={active:false,mode:'sonar',busy:false,sonar:null,corr:null,lastPing:0,dop:{tx:false,tracking:false,baseline:2000,obs:0,vel:0,snr:0,history:[],last:0},range:{selected:'A',turn:120,armed:false,last:null},pos:null,hist:[],live:false,anchors};
function save(){try{localStorage.setItem('ss_acoustic_anchors_v1',JSON.stringify(anchors.map(a=>({id:a.id,x:a.x,y:a.y,range:a.range,bias:a.bias,q:a.q}))))}catch(_){}}
$('acousticControlMount').innerHTML='<div class="acp-family"><div class="acp-family-head"><span>ACOUSTIC PHYSICS</span><small>Echo · Motion · Ranging · Position</small></div><div class="acp-runtime"><span id="apPerfBadge">PERF</span><select id="apPerf"><option value="auto">Auto</option><option value="full">FULL · i5 Gen-12+</option><option value="eco">ECO · Android / IFP</option></select></div><div class="acp-modes">'+[['sonar','📡 Echo Sonar'],['doppler','↔ Doppler'],['ranging','📍 Multi-Anchor'],['position','◎ Position Radar']].map(([m,l])=>'<button class="btn" data-ap-mode="'+m+'">'+l+'</button>').join('')+'</div></div><div id="acpControls"></div>';
$('acousticStage').innerHTML='<div class="acp-stage-head"><div><span class="acp-kicker">PILAR · ACOUSTIC INSTRUMENTATION PLATFORM</span><h2 id="apTitle">—</h2></div><span class="acp-live" id="apLive"><i></i><b id="apLiveText">READY</b></span></div><div class="acp-chain" id="apChain"></div><div class="acp-stage-body" id="apBody"></div><div class="acp-aha" id="apAha"></div>';
function live(on,label){$('apLive').classList.toggle('on',!!on);$('apLiveText').textContent=label}function chain(items){$('apChain').innerHTML=items.map((x,i)=>'<span>'+x+'</span>'+(i<items.length-1?'<i>→</i>':'')).join('')}
function stopActivities(){S.live=false;S.dop.tracking=false;if(S.dop.tx){E.stopTone();S.dop.tx=false}if(S.range.armed){E.stopResponder();S.range.armed=false}live(false,'READY')}
function setMode(m){stopActivities();S.mode=m;document.querySelectorAll('[data-ap-mode]').forEach(b=>b.classList.toggle('on',b.dataset.apMode===m));renderControls();renderStage();requestAnimationFrame(fit)}
document.querySelectorAll('[data-ap-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.apMode));const perfSel=$('apPerf');if(perfSel){perfSel.value=PERF.choice;perfSel.onchange=e=>setPerfChoice(e.target.value)}perfLabel();const temp=()=>+($('apTemp')?.value||27);
function renderControls(){const el=$('acpControls');
 if(S.mode==='sonar')el.innerHTML='<div class="card"><b>📡 Echo Sonar</b><div class="hint">Bunyi langsung dan gema direkam pada sample clock yang sama. Mode v1 aman mulai sekitar 0,6 m.</div><div class="acp-grid"><label>Suhu (°C)<input id="apTemp" type="number" value="27"></label><label>Range<select id="apRange"><option value="3">0–3 m</option><option value="5" selected>0–5 m</option><option value="8">0–8 m</option></select></label><label>Baseline speaker↔mic (cm)<input id="apBase" type="number" value="0"></label><label>Volume<select id="apVol"><option value=".20">Rendah</option><option value=".28" selected>Sedang</option><option value=".36">Agak kuat</option></select></label></div><div class="acp-actions tri"><button class="btn good" id="apPing">◉ PING ×3</button><button class="btn good" id="apLiveBtn">⟳ Live</button><button class="btn primary" id="apDemo">▶ Demo 2,0 m</button></div><div class="acp-status" id="apStatus">Gunakan speaker bawaan; hindari Bluetooth.</div></div><div class="card acp-readout"><b>HASIL</b><div><small>JARAK</small><strong id="apDistance">—</strong></div><div><small>Δt</small><strong id="apDt">—</strong></div><div><small>c</small><strong id="apC">—</strong></div><div><small>KUALITAS</small><strong id="apQ">—</strong></div></div>';
 else if(S.mode==='doppler')el.innerHTML='<div class="card"><b>↔ Doppler Lab</b><div class="hint">Dua perangkat: HP sebagai TX, IFP sebagai RX. Kalibrasi diam menghapus offset oscillator/sample-clock.</div><div class="acp-grid"><label>Carrier<select id="dpFreq"><option>1500</option><option selected>2000</option><option>2500</option><option>3000</option></select></label><label>Suhu (°C)<input id="apTemp" type="number" value="27"></label></div><div class="acp-actions quad"><button class="btn good" id="dpTx">▶ TX NADA</button><button class="btn danger" id="dpStop">■ Stop TX</button><button class="btn primary" id="dpCal">◎ Kalibrasi diam</button><button class="btn good" id="dpTrack">↔ Mulai tracking</button></div><div class="acp-status" id="apStatus">RX: diamkan sumber lalu tekan Kalibrasi.</div></div><div class="card acp-readout"><b>DOPPLER</b><div><small>BASELINE</small><strong id="dpBase">—</strong></div><div><small>TERIMA</small><strong id="dpObs">—</strong></div><div><small>Δf</small><strong id="dpShift">—</strong></div><div><small>KECEPATAN</small><strong id="dpVel">—</strong></div></div>';
 else if(S.mode==='ranging')el.innerHTML='<div class="card"><b>📍 Multi-Anchor Ranging</b><div class="hint">HP Anchor membalas poll otomatis setelah 120 ms di AudioWorklet. Tiap anchor mempunyai pasangan frekuensi unik.</div><div class="acp-grid"><label>Anchor<select id="rgId">'+anchors.map(a=>'<option>'+a.id+'</option>').join('')+'</select></label><label>Suhu (°C)<input id="apTemp" type="number" value="27"></label><label>Jarak kalibrasi (m)<input id="rgRef" type="number" value="1" step=".1"></label></div><div class="acp-actions quad"><button class="btn good" id="rgArm">📡 ARM ANCHOR</button><button class="btn primary" id="rgOne">◎ Ukur terpilih</button><button class="btn primary" id="rgAll">◎ Ukur semua</button><button class="btn warn" id="rgCal">⚙ Kalibrasi</button></div><div class="acp-status" id="apStatus">Di HP pilih ID lalu ARM. Di IFP tekan Ukur.</div></div><div class="card"><b>ANCHOR TABLE</b><div class="anchor-table" id="rgTable"></div></div>';
 else el.innerHTML='<div class="card"><b>◎ Position Radar</b><div class="hint">Gabungkan minimal tiga range. Solver least-squares menampilkan posisi dan residual tiap anchor.</div><div class="acp-actions"><button class="btn good" id="psSolve">◎ Hitung posisi</button><button class="btn primary" id="psDemo">▶ Demo target</button></div><div class="acp-status" id="apStatus">Range dari Multi-Anchor otomatis dibawa ke sini.</div></div><div class="card"><b>KOORDINAT & RANGE</b><div class="anchor-table" id="psTable"></div></div>';
 bindControls()}
function renderRangeTable(){const t=$('rgTable');if(t)t.innerHTML=anchors.map(a=>'<div class="anchor-row simple"><b>'+a.id+'</b><span>'+a.poll+'→'+a.reply+' Hz</span><span>'+(a.range==null?'—':a.range.toFixed(2)+' m')+'</span><span>bias '+a.bias.toFixed(2)+' m</span></div>').join('')}
function renderPositionTable(){const t=$('psTable');if(!t)return;t.innerHTML=anchors.map(a=>'<div class="anchor-row"><b>'+a.id+'</b><label>X<input data-a="'+a.id+'" data-k="x" type="number" step=".1" value="'+a.x+'"></label><label>Y<input data-a="'+a.id+'" data-k="y" type="number" step=".1" value="'+a.y+'"></label><label>Range<input data-a="'+a.id+'" data-k="range" type="number" step=".01" value="'+(a.range??'')+'" placeholder="—"></label><span class="anchor-q">'+(a.range==null?'—':a.range.toFixed(2)+' m')+'</span></div>').join('');t.querySelectorAll('input[data-a]').forEach(i=>i.onchange=()=>{const a=anchors.find(x=>x.id===i.dataset.a),v=parseFloat(i.value),k=i.dataset.k;a[k]=Number.isFinite(v)?v:(k==='range'?null:a[k]);save();solvePosition(false)})}
function bindControls(){if(S.mode==='sonar'){$('apPing').onclick=()=>sonarPing(3);$('apLiveBtn').onclick=toggleLive;$('apDemo').onclick=sonarDemo}if(S.mode==='doppler'){$('dpTx').onclick=dopplerTx;$('dpStop').onclick=()=>{E.stopTone();S.dop.tx=false;live(false,'TX OFF')};$('dpCal').onclick=dopplerCalibrate;$('dpTrack').onclick=()=>{S.dop.tracking=!S.dop.tracking;$('dpTrack').textContent=S.dop.tracking?'■ Stop tracking':'↔ Mulai tracking';live(S.dop.tracking,S.dop.tracking?'TRACKING':'READY')}}if(S.mode==='ranging'){$('rgId').value=S.range.selected;$('rgId').onchange=e=>S.range.selected=e.target.value;$('rgArm').onclick=armAnchor;$('rgOne').onclick=()=>measureAnchor(S.range.selected,false);$('rgAll').onclick=measureAll;$('rgCal').onclick=calibrateAnchor;renderRangeTable()}if(S.mode==='position'){$('psSolve').onclick=()=>solvePosition(true);$('psDemo').onclick=positionDemo;renderPositionTable()}}
function renderStage(){const body=$('apBody');if(S.mode==='sonar'){$('apTitle').innerHTML='Echo Sonar <em>range only</em>';chain(['PANCARKAN','RAMBAT','TERIMA','UKUR Δt','JARAK']);body.innerHTML='<div class="acp-viz"><div class="acp-radar-wrap"><canvas id="apMain"></canvas><div class="acp-overlay"><b id="apHero">—</b><small>RANGE ONLY · ANGLE UNKNOWN</small></div></div><div class="acp-corr-wrap"><div class="acp-cap">MATCHED FILTER · DIRECT vs ECHO</div><canvas id="apAux"></canvas></div></div>';$('apAha').textContent='AHA: jarak berasal dari jeda bunyi langsung dan gema.'}else if(S.mode==='doppler'){$('apTitle').innerHTML='Doppler Lab <em>motion from Δf</em>';chain(['NADA ACUAN','GERAK','Δf','HITUNG v','ARAH']);body.innerHTML='<div class="acp-viz"><div class="acp-radar-wrap"><canvas id="apMain"></canvas><div class="acp-overlay"><b id="apHero">0.00 m/s</b><small>+ MENDEKAT · − MENJAUH</small></div></div><div class="acp-corr-wrap"><div class="acp-cap">FREQUENCY TRACE · Hz vs waktu</div><canvas id="apAux"></canvas></div></div>';$('apAha').textContent='AHA: gerak muncul sebagai pergeseran frekuensi beberapa hertz.'}else if(S.mode==='ranging'){$('apTitle').innerHTML='Multi-Anchor Ranging <em>two-way acoustic</em>';chain(['POLL','ANCHOR','DELAY TETAP','REPLY','RANGE']);body.innerHTML='<div class="acp-viz one"><div class="acp-corr-wrap"><div class="acp-cap">PAIRWISE TIMING</div><canvas id="apMain"></canvas></div><div class="anchor-stage" id="apAnchorStage"></div></div>';$('apAha').textContent='AHA: round-trip diukur pada satu sample clock; jam antardevice tidak perlu sinkron.'}else{$('apTitle').innerHTML='Position Radar <em>multilateration 2D</em>';chain(['RANGE A–D','LINGKARAN','SOLVER','RESIDUAL','POSISI']);body.innerHTML='<div class="acp-viz"><div class="acp-radar-wrap"><canvas id="apMain"></canvas><div class="acp-overlay"><b id="apHero">—</b><small>MULTI-ANCHOR POSITION</small></div></div><div class="acp-corr-wrap"><div class="acp-cap">RESIDUAL · model − measured</div><canvas id="apAux"></canvas></div></div>';$('apAha').textContent='AHA: posisi adalah titik yang paling konsisten dengan beberapa jarak.'}}
let main,aux,mc,xc;function fit(){main=$('apMain');aux=$('apAux');for(const c of [main,aux].filter(Boolean)){const r=c.getBoundingClientRect(),d=Math.min(PERF.dprMax,devicePixelRatio||1);c.width=Math.max(10,Math.round(r.width*d));c.height=Math.max(10,Math.round(r.height*d));c._d=d}mc=main?.getContext('2d')||null;xc=aux?.getContext('2d')||null}
async function sonarPing(n=3){if(S.busy)return;S.busy=true;live(true,n>1?'PING ×'+n:'LIVE');try{await E.ensure();await sleep(90);const chirp=C.makeChirp({sr:E.sr,durationMs:10,f0:2200,f1:7000,amp:.9}),opt={sr:E.sr,tempC:temp(),baselineM:Math.max(0,(+$('apBase').value||0)/100),maxRangeM:+$('apRange').value||5,minRangeM:.5,searchStartMs:20,searchEndMs:330},res=[];
 for(let k=0;k<n;k++){const mark=E.mark();S.lastPing=performance.now();await E.playSamples(chirp,+$('apVol').value||.28,75);await sleep(400);res.push(await analyzeSonarAsync(E.slice(mark,E.mark()),opt));if(k<n-1)await sleep(100)}
 const oks=res.filter(r=>r.ok).sort((a,b)=>a.distanceM-b.distanceM),r=oks.length?oks[oks.length>>1]:res[res.length-1];if(oks.length){r.spread=oks[oks.length-1].distanceM-oks[0].distanceM;r.votes=oks.length+'/'+n}
 S.sonar=r;S.corr=r.correlation;updateSonar(r);$('apStatus').textContent=r.ok?'✓ '+r.distanceM.toFixed(2)+' m'+(n>1?' ± '+(r.spread/2*100).toFixed(1)+' cm · '+r.votes+' ping valid':'')+' · SNR '+r.snr.toFixed(0)+'×':'Belum dapat jarak: '+r.reason;live(false,r.ok?'ECHO LOCK':'NO LOCK')}catch(e){$('apStatus').textContent='Sonar gagal: '+(e.message||e);live(false,'ERROR')}finally{S.busy=false}}
function toggleLive(){S.live=!S.live;const b=$('apLiveBtn');if(b)b.textContent=S.live?'■ Stop live':'⟳ Live';if(S.live)liveLoop()}
async function liveLoop(){while(S.live&&S.active&&S.mode==='sonar'){await sonarPing(1);await sleep(PERF.livePause)}S.live=false;const b=$('apLiveBtn');if(b)b.textContent='⟳ Live'}
function sonarDemo(){const chirp=C.makeChirp({sr:48000,durationMs:10,f0:2200,f1:7000,amp:.9}),sim=C.synthEcho({sr:48000,chirp,distanceM:2,tempC:27,noise:.006,echoAmp:.18,reflections:2}),r=C.analyzeEcho(sim.samples,chirp,{sr:48000,tempC:27,maxRangeM:5,minRangeM:.5,searchStartMs:20,searchEndMs:330});S.sonar=r;S.corr=r.correlation;S.lastPing=performance.now();updateSonar(r);$('apStatus').textContent='Demo sintetis 2,00 m.'}function updateSonar(r){if(!$('apC'))return;$('apC').textContent=C.speedOfSound(temp()).toFixed(1)+' m/s';if(!r?.ok)return;S.hist.push({d:r.distanceM,t:performance.now()});while(S.hist.length>PERF.trailMax)S.hist.shift();$('apDistance').textContent=r.distanceM.toFixed(2)+' m';$('apDt').textContent=(r.dt*1000).toFixed(2)+' ms';$('apQ').textContent=Math.round(r.confidence*100)+'%';if($('apHero'))$('apHero').textContent=r.distanceM.toFixed(2)+' m'}
function dopplerTx(){const f=+$('dpFreq').value||2000;S.dop.tracking=false;E.startTone(f,.14);S.dop.tx=true;live(true,'TX '+f+' Hz');$('apStatus').textContent='TX aktif. Gunakan volume sedang dan gerak lurus.'}async function dopplerSample(){await E.ensure();const x=E.recent(140);if(x.length<E.sr*.08)return null;return C.estimateTone(x,{sr:E.sr,center:+$('dpFreq').value||2000,span:45,step:1,minSnrDb:5})}
async function dopplerCalibrate(){try{E.stopTone();S.dop.tx=false;live(true,'CALIBRATING');await E.ensure();await sleep(300);const vals=[];for(let i=0;i<10;i++){const r=await dopplerSample();if(r?.ok)vals.push(r.freq);await sleep(110)}if(vals.length<5)throw Error('carrier belum cukup jelas');S.dop.baseline=vals.reduce((a,b)=>a+b,0)/vals.length;$('dpBase').textContent=S.dop.baseline.toFixed(2)+' Hz';$('apStatus').textContent='Kalibrasi selesai. Mulai tracking.';live(false,'CAL OK')}catch(e){$('apStatus').textContent='Kalibrasi gagal: '+(e.message||e);live(false,'NO LOCK')}}
async function dopplerTick(now){if(!S.dop.tracking||now-S.dop.last<120)return;S.dop.last=now;const r=await dopplerSample();if(!r?.ok)return;const d=C.dopplerVelocity(r.freq,S.dop.baseline,temp());S.dop.obs=r.freq;S.dop.vel=.72*S.dop.vel+.28*d.velocity;S.dop.snr=r.snrDb;S.dop.history.push({t:now,f:r.freq,v:S.dop.vel});while(S.dop.history.length>90)S.dop.history.shift();if($('dpObs')){$('dpBase').textContent=S.dop.baseline.toFixed(2)+' Hz';$('dpObs').textContent=r.freq.toFixed(2)+' Hz';$('dpShift').textContent=(r.freq-S.dop.baseline>=0?'+':'')+(r.freq-S.dop.baseline).toFixed(2)+' Hz';$('dpVel').textContent=(S.dop.vel>=0?'+':'')+S.dop.vel.toFixed(2)+' m/s';$('apStatus').textContent=r.snrDb.toFixed(0)+' dB · '+(S.dop.vel>.15?'mendekat':S.dop.vel<-.15?'menjauh':'hampir diam')}}
const selected=()=>anchors.find(a=>a.id===S.range.selected)||anchors[0];async function armAnchor(){try{const a=selected();if(S.range.armed){E.stopResponder();S.range.armed=false;$('rgArm').textContent='📡 ARM ANCHOR';live(false,'ANCHOR OFF');return}await E.setResponder({pollFreq:a.poll,replyFreq:a.reply,delayMs:S.range.turn,replyMs:24,amp:.26,minAmp:.006,compMs:4.9});S.range.armed=true;$('rgArm').textContent='■ STOP ANCHOR';$('apStatus').textContent='Anchor '+a.id+' armed: '+a.poll+' → '+a.reply+' Hz.';live(true,'ANCHOR '+a.id)}catch(e){$('apStatus').textContent='Gagal arm: '+(e.message||e)}}
async function rawRange(a){await E.ensure();E.stopResponder();await sleep(80);const mark=E.mark();await E.playToneBurst(a.poll,24,.24,75);await sleep(500);const x=E.slice(mark,E.mark()),p=C.detectToneOnset(x,{sr:E.sr,freq:a.poll,winMs:6,hopMs:.5,ratio:.5,consecutive:2}),q=C.detectToneOnset(x,{sr:E.sr,freq:a.reply,winMs:6,hopMs:.5,ratio:.5,consecutive:2});if(!p.ok||!q.ok||q.exact<=p.exact)throw Error('poll/reply belum terdeteksi');const dt=(q.exact-p.exact)/E.sr,rr=C.rangeFromRoundTrip(dt,S.range.turn,temp(),0);return {rawM:rr.rawM,dt,poll:p,reply:q}}
async function rawRangeMed(a,n=3){const rs=[];for(let k=0;k<n;k++){try{rs.push(await rawRange(a))}catch(e){if(k===n-1&&!rs.length)throw e}await sleep(140)}rs.sort((x,y)=>x.rawM-y.rawM);const m=rs[rs.length>>1];m.spread=rs[rs.length-1].rawM-rs[0].rawM;m.votes=rs.length+'/'+n;return m}
async function measureAnchor(id,calOnly){if(S.busy)return null;S.busy=true;const a=anchors.find(x=>x.id===id);S.range.selected=id;live(true,'RANGE '+id);try{const r=await rawRangeMed(a,3);if(!calOnly){a.range=Math.max(0,r.rawM-a.bias);a.q=Math.min(r.poll.confidence,r.reply.confidence);S.range.last={id,...r,distance:a.range};save();renderRangeTable();renderAnchorStage();$('apStatus').textContent='✓ '+id+' = '+a.range.toFixed(2)+' m ± '+(r.spread/2*100).toFixed(1)+' cm · '+r.votes+' putaran'}live(false,'RANGE OK');return r}catch(e){$('apStatus').textContent=id+' gagal: '+(e.message||e);live(false,'NO REPLY');return null}finally{S.busy=false}}
async function measureAll(){for(const a of anchors){S.range.selected=a.id;if($('rgId'))$('rgId').value=a.id;await measureAnchor(a.id,false);await sleep(220)}}async function calibrateAnchor(){const a=selected(),ref=Math.max(.5,+$('rgRef').value||1),r=await measureAnchor(a.id,true);if(r){a.bias=r.rawM-ref;save();renderRangeTable();$('apStatus').textContent='✓ bias '+a.id+' = '+a.bias.toFixed(2)+' m'}}
function renderAnchorStage(){const el=$('apAnchorStage');if(el)el.innerHTML=anchors.map(a=>'<div class="anchor-tile '+(a.range!=null?'ok':'')+'"><b>'+a.id+'</b><span>'+(a.range==null?'WAIT':a.range.toFixed(2)+' m')+'</span><small>'+a.poll+'→'+a.reply+' Hz</small></div>').join('')}
function solvePosition(show){const pts=anchors.filter(a=>a.range!=null).map(a=>({id:a.id,x:+a.x,y:+a.y,r:+a.range,w:a.q?(.4+.6*a.q):1})),r=C.trilaterate(pts);S.pos=r;if(show&&$('apStatus'))$('apStatus').textContent=r.ok?'✓ Posisi '+r.x.toFixed(2)+', '+r.y.toFixed(2)+' m · RMS '+r.rms.toFixed(2)+' m':'Belum bisa: '+r.reason;if($('apHero'))$('apHero').textContent=r.ok?r.x.toFixed(2)+', '+r.y.toFixed(2)+' m':'—';return r}function positionDemo(){const tx=2.4,ty=1.7;anchors.forEach((a,i)=>{a.range=Math.hypot(tx-a.x,ty-a.y)+[.01,-.02,.03,-.015][i];a.q=.9});save();renderPositionTable();solvePosition(true);$('apStatus').textContent+=' · target demo 2,40 × 1,70 m.'}
function drawGrid(ctx,W,H){ctx.strokeStyle='rgba(126,238,255,.1)';for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(0,H*i/5);ctx.lineTo(W,H*i/5);ctx.stroke()}}
const CY='126,238,255',GD='99,227,160',AM='255,211,108',BL='105,186,255',TXT='#9db2ca',FONT='600 11px ui-sans-serif,system-ui,sans-serif';
function setup(cv,ctx){const d=cv._d||1;ctx.setTransform(d,0,0,d,0,0);const W=cv.width/d,H=cv.height/d;ctx.clearRect(0,0,W,H);ctx.font=FONT;return [W,H]}
function glowDot(ctx,x,y,r,rgb){const g=ctx.createRadialGradient(x,y,0,x,y,r*3.2);g.addColorStop(0,'rgba('+rgb+',.55)');g.addColorStop(1,'rgba('+rgb+',0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r*3.2,0,7);ctx.fill();ctx.fillStyle='rgb('+rgb+')';ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill()}
function drawSonar(now){if(!mc)return;const [W,H]=setup(main,mc),cx=W/2,cy=H*.54,R=Math.min(W*.44,H*.40),max=+$('apRange')?.value||5,r=S.sonar,hit=r?.ok;
 const bg=mc.createRadialGradient(cx,cy,0,cx,cy,R*1.2);bg.addColorStop(0,'rgba('+CY+',.10)');bg.addColorStop(1,'rgba('+CY+',0)');mc.fillStyle=bg;mc.beginPath();mc.arc(cx,cy,R*1.2,0,7);mc.fill();
 mc.textAlign='center';mc.lineWidth=1;for(let i=1;i<=5;i++){mc.strokeStyle='rgba('+CY+','+(i===5?.4:.14)+')';mc.beginPath();mc.arc(cx,cy,R*i/5,0,7);mc.stroke();mc.fillStyle=TXT;mc.fillText((max*i/5).toFixed(max<=3?1:0)+' m',cx,cy-R*i/5-4)}
 mc.strokeStyle='rgba('+CY+',.08)';mc.beginPath();for(let k=0;k<12;k++){const a=k*Math.PI/6;mc.moveTo(cx,cy);mc.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R)}mc.stroke();
 const a0=(now/2800)%(Math.PI*2);if(mc.createConicGradient){const g=mc.createConicGradient(a0,cx,cy);g.addColorStop(0,'rgba('+GD+',0)');g.addColorStop(.09,'rgba('+GD+',.20)');g.addColorStop(.091,'rgba('+GD+',0)');mc.fillStyle=g;mc.beginPath();mc.arc(cx,cy,R,0,7);mc.fill();mc.strokeStyle='rgba('+GD+',.5)';mc.beginPath();mc.moveTo(cx,cy);mc.lineTo(cx+Math.cos(a0+.571)*R,cy+Math.sin(a0+.571)*R);mc.stroke()}
 const now2=performance.now();S.hist.forEach(h=>{const age=(now2-h.t)/PERF.trailMs;if(age>1)return;mc.strokeStyle='rgba('+AM+','+(.5*(1-age)).toFixed(3)+')';mc.lineWidth=2;mc.beginPath();mc.arc(cx,cy,clamp(h.d/max,0,1)*R,0,7);mc.stroke()});
 const Rt=hit?clamp(r.distanceM/max,0,1)*R:R;if(S.lastPing){const p=(now-S.lastPing)/1700;if(p<1){const out=p<.5,rad=(out?p/.5:1-(p-.5)/.5)*Rt;mc.lineWidth=out?2.5:1.5;mc.strokeStyle='rgba('+(out?BL:AM)+','+(out?.7:.55)*(1-p*.5)+')';mc.beginPath();mc.arc(cx,cy,Math.max(1,rad),0,7);mc.stroke();mc.fillStyle=TXT;mc.fillText(out?'bunyi pergi →':'← gema kembali',cx,cy+R+22)}}
 if(hit){mc.save();mc.shadowColor='rgba('+AM+',.9)';mc.shadowBlur=18;mc.strokeStyle='rgb('+AM+')';mc.lineWidth=3.5;mc.beginPath();mc.arc(cx,cy,Rt,0,7);mc.stroke();mc.restore();const an=-Math.PI/4,lx=cx+Math.cos(an)*Rt,ly=cy+Math.sin(an)*Rt;glowDot(mc,lx,ly,4,AM);mc.fillStyle='#eef7ff';mc.textAlign='left';mc.fillText(r.distanceM.toFixed(2)+' m',lx+10,ly-6);mc.textAlign='center'}
 glowDot(mc,cx,cy,5,GD);mc.fillStyle=TXT;mc.fillText('IFP / laptop',cx,cy+18)}
function drawCorr(){if(!xc)return;const [W,H]=setup(aux,xc),L=44,Rr=14,T=34,B=30,w=W-L-Rr,h=H-T-B;xc.strokeStyle='rgba('+CY+',.1)';xc.lineWidth=1;for(let i=0;i<=4;i++){const y=T+h*i/4;xc.beginPath();xc.moveTo(L,y);xc.lineTo(L+w,y);xc.stroke()}
 const c=S.corr;if(!c?.values?.length){xc.fillStyle=TXT;xc.textAlign='center';xc.fillText('Tekan PING atau Demo untuk melihat matched filter',W/2,H/2);return}
 const a=c.values,sr=c.sr||E.sr||48000,r=S.sonar,mx=Math.max(1e-9,...a),n=a.length,px=Math.max(1,Math.floor(n/w)),X=i=>L+(i-c.offset)/n*w,Y=v=>T+h-v/mx*h;
 const g=xc.createLinearGradient(0,T,0,T+h);g.addColorStop(0,'rgba('+BL+',.45)');g.addColorStop(1,'rgba('+BL+',0)');xc.beginPath();xc.moveTo(L,T+h);for(let x=0;x<w;x++){let m=0;for(let j=0;j<px&&x*px+j<n;j++)m=Math.max(m,a[x*px+j]);xc.lineTo(L+x,Y(m))}xc.lineTo(L+w,T+h);xc.closePath();xc.fillStyle=g;xc.fill();
 xc.beginPath();for(let x=0;x<w;x++){let m=0;for(let j=0;j<px&&x*px+j<n;j++)m=Math.max(m,a[x*px+j]);x?xc.lineTo(L+x,Y(m)):xc.moveTo(L+x,Y(m))}xc.strokeStyle='rgb('+BL+')';xc.lineWidth=1.6;xc.stroke();
 if(r?.floor){xc.setLineDash([4,4]);xc.strokeStyle='rgba(255,109,131,.7)';const y=Y(Math.min(mx,r.floor*4.5));xc.beginPath();xc.moveTo(L,y);xc.lineTo(L+w,y);xc.stroke();xc.setLineDash([]);xc.fillStyle='rgba(255,109,131,.9)';xc.textAlign='right';xc.fillText('ambang deteksi',L+w,y-4)}
 const mark=(p,col,lab,dy)=>{if(!p)return;const x=X(p.i+(p.f||0));xc.strokeStyle=col;xc.lineWidth=1.5;xc.beginPath();xc.moveTo(x,T);xc.lineTo(x,T+h);xc.stroke();glowDot(xc,x,Y(p.v),3,col===('rgb('+GD+')')?GD:AM);xc.fillStyle=col;xc.textAlign='left';xc.fillText(lab,x+6,T+12+dy)};
 mark(r?.direct,'rgb('+GD+')','LANGSUNG',0);if(r?.ok){mark(r.echo,'rgb('+AM+')','GEMA +'+(r.dt*1000).toFixed(2)+' ms',14);const x1=X(r.direct.i+r.direct.f),x2=X(r.echo.i+r.echo.f);xc.strokeStyle='rgba('+AM+',.8)';xc.beginPath();xc.moveTo(x1,T+h-8);xc.lineTo(x2,T+h-8);xc.stroke();xc.fillStyle='rgb('+AM+')';xc.textAlign='center';xc.fillText('Δt → '+r.distanceM.toFixed(2)+' m',(x1+x2)/2,T+h-14)}
 xc.fillStyle=TXT;xc.textAlign='center';for(let i=0;i<=5;i++){const ms=(c.offset+n*i/5)/sr*1000;xc.fillText(ms.toFixed(0)+' ms',L+w*i/5,H-10)}xc.textAlign='right';xc.fillText('amplitudo',L-6,T+10)}

function drawDoppler(){if(!mc||!xc)return;let d=main._d||1,W=main.width/d,H=main.height/d,cx=W/2,cy=H*.58,r=Math.min(W,H)*.31,v=clamp(S.dop.vel,-3,3),ang=-Math.PI/2+v/3*Math.PI*.75;mc.setTransform(d,0,0,d,0,0);mc.clearRect(0,0,W,H);mc.strokeStyle='rgba(126,238,255,.18)';mc.lineWidth=14;mc.beginPath();mc.arc(cx,cy,r,-Math.PI/2-Math.PI*.75,-Math.PI/2+Math.PI*.75);mc.stroke();mc.fillStyle='#9db2ca';mc.textAlign='center';mc.fillText('0',cx,cy-r-14);mc.fillText('+3 m/s',cx+Math.cos(Math.PI/4)*(r+34),cy+Math.sin(Math.PI/4)*(r+24));mc.fillText('−3 m/s',cx-Math.cos(Math.PI/4)*(r+34),cy+Math.sin(Math.PI/4)*(r+24));mc.strokeStyle=v>.15?'#63e3a0':v<-.15?'#69baff':'#ffd36c';mc.lineWidth=5;mc.beginPath();mc.moveTo(cx,cy);mc.lineTo(cx+Math.cos(ang)*r*.85,cy+Math.sin(ang)*r*.85);mc.stroke();if($('apHero'))$('apHero').textContent=(v>=0?'+':'')+v.toFixed(2)+' m/s';d=aux._d||1;W=aux.width/d;H=aux.height/d;xc.setTransform(d,0,0,d,0,0);xc.clearRect(0,0,W,H);drawGrid(xc,W,H);const h=S.dop.history;if(h.length<2)return;const f0=S.dop.baseline||2000,span=18;xc.strokeStyle='#7eeeff';xc.lineWidth=2;xc.beginPath();h.forEach((p,i)=>{const x=20+i/Math.max(1,h.length-1)*(W-40),y=H/2-(p.f-f0)/span*(H*.42);i?xc.lineTo(x,y):xc.moveTo(x,y)});xc.stroke()}
function drawRanging(){if(!mc)return;const [W,H]=setup(main,mc),L=84,R=W-30,r=S.range.last,yI=H*.34,yA=H*.68;
 [[yI,'IFP (poller)',GD],[yA,'ANCHOR',BL]].forEach(([y,l,c])=>{mc.strokeStyle='rgba('+c+',.35)';mc.lineWidth=2;mc.beginPath();mc.moveTo(L,y);mc.lineTo(R,y);mc.stroke();mc.fillStyle='rgb('+c+')';mc.textAlign='right';mc.fillText(l,L-10,y+4)});
 if(!r){mc.fillStyle=TXT;mc.textAlign='center';mc.fillText('ARM anchor di HP, lalu tekan Ukur di IFP',W/2,H/2);return}
 const tur=S.range.turn/1000,tot=r.dt*1.08,X=t=>L+t/tot*(R-L),trav=(r.dt-tur)/2,pts=[[0,yI],[trav,yA],[trav+tur,yA],[r.dt,yI]];
 mc.fillStyle='rgba('+AM+',.14)';mc.fillRect(X(trav),yA-16,X(trav+tur)-X(trav),32);mc.fillStyle='rgb('+AM+')';mc.textAlign='center';mc.fillText('tunda tetap '+S.range.turn+' ms',(X(trav)+X(trav+tur))/2,yA+30);
 [[0,1,GD,'POLL →'],[2,3,BL,'← REPLY']].forEach(([i,j,c,l])=>{const x1=X(pts[i][0]),y1=pts[i][1],x2=X(pts[j][0]),y2=pts[j][1];mc.strokeStyle='rgb('+c+')';mc.lineWidth=2.5;mc.setLineDash([6,4]);mc.beginPath();mc.moveTo(x1,y1);mc.lineTo(x2,y2);mc.stroke();mc.setLineDash([]);mc.fillStyle='rgb('+c+')';mc.textAlign='center';mc.fillText(l+' '+(trav*1000).toFixed(1)+' ms',(x1+x2)/2+(i?24:-24),(y1+y2)/2)});
 pts.forEach(([t,y],i)=>glowDot(mc,X(t),y,4,i%3===0?GD:BL));mc.fillStyle='#eef7ff';mc.textAlign='left';mc.font='800 13px ui-sans-serif,system-ui';mc.fillText('d = c × (Δt − tunda) / 2 = '+(r.distance??r.rawM).toFixed(2)+' m',L,H-18);mc.font=FONT}
function drawPosition(){if(!mc||!xc)return;const [W,H]=setup(main,mc),xs=anchors.map(a=>a.x),ys=anchors.map(a=>a.y),r=S.pos||solvePosition(false),ex=r?.ok?[r.x]:[],ey=r?.ok?[r.y]:[],x0=Math.min(0,...xs,...ex),x1=Math.max(1,...xs,...ex),y0=Math.min(0,...ys,...ey),y1=Math.max(1,...ys,...ey),pad=44,s=Math.min((W-2*pad)/(x1-x0),(H-2*pad)/(y1-y0)),ox=(W-(x1-x0)*s)/2,oy=(H+(y1-y0)*s)/2,tx=x=>ox+(x-x0)*s,ty=y=>oy-(y-y0)*s;
 mc.lineWidth=1;mc.textAlign='center';for(let x=Math.ceil(x0);x<=x1;x++){mc.strokeStyle='rgba('+CY+','+(x===0?.3:.09)+')';mc.beginPath();mc.moveTo(tx(x),ty(y0));mc.lineTo(tx(x),ty(y1));mc.stroke();mc.fillStyle=TXT;mc.fillText(x+' m',tx(x),ty(y0)+16)}
 for(let y=Math.ceil(y0);y<=y1;y++){mc.strokeStyle='rgba('+CY+','+(y===0?.3:.09)+')';mc.beginPath();mc.moveTo(tx(x0),ty(y));mc.lineTo(tx(x1),ty(y));mc.stroke();mc.textAlign='right';mc.fillStyle=TXT;mc.fillText(y+' m',tx(x0)-6,ty(y)+4)}
 anchors.forEach(a=>{const x=tx(a.x),y=ty(a.y);if(a.range!=null){mc.strokeStyle='rgba('+BL+',.35)';mc.lineWidth=1.5;mc.beginPath();mc.arc(x,y,a.range*s,0,7);mc.stroke();if(r?.ok){mc.strokeStyle='rgba('+AM+',.25)';mc.setLineDash([3,4]);mc.beginPath();mc.moveTo(x,y);mc.lineTo(tx(r.x),ty(r.y));mc.stroke();mc.setLineDash([])}}glowDot(mc,x,y,5,GD);mc.fillStyle='#eef7ff';mc.textAlign='left';mc.fillText(a.id,x+10,y-9)});
 if(r?.ok){const x=tx(r.x),y=ty(r.y);mc.strokeStyle='rgba('+AM+',.5)';mc.lineWidth=1.5;mc.beginPath();mc.arc(x,y,Math.max(8,r.uncertainty*s),0,7);mc.stroke();glowDot(mc,x,y,6,AM);mc.fillStyle='rgb('+AM+')';mc.textAlign='left';mc.fillText('TARGET ('+r.x.toFixed(2)+', '+r.y.toFixed(2)+')',x+12,y+16)}
 const [W2,H2]=setup(aux,xc);if(!r?.ok){xc.fillStyle=TXT;xc.textAlign='center';xc.fillText('Butuh ≥3 range anchor',W2/2,H2/2);return}
 const mr=Math.max(.05,...r.residuals.map(z=>Math.abs(z.residual))),bw=(W2-70)/r.residuals.length,mid=H2/2;xc.strokeStyle='rgba('+CY+',.3)';xc.beginPath();xc.moveTo(34,mid);xc.lineTo(W2-16,mid);xc.stroke();
 r.residuals.forEach((z,i)=>{const x=40+i*bw+bw*.18,h=z.residual/mr*(H2*.33);xc.fillStyle=Math.abs(z.residual)<.05?'rgba('+GD+',.8)':z.residual>=0?'rgba(255,109,131,.85)':'rgba('+BL+',.85)';xc.fillRect(x,h>=0?mid-h:mid,bw*.64,Math.abs(h));xc.fillStyle='#eef7ff';xc.textAlign='center';xc.fillText(z.id,x+bw*.32,H2-10);xc.fillStyle=TXT;xc.fillText((z.residual>=0?'+':'')+(z.residual*100).toFixed(1)+' cm',x+bw*.32,h>=0?mid-h-5:mid-h+14)})}

function tick(now){if(!S.active)return;if(S.mode==='doppler')dopplerTick(now);if(now-lastDraw<PERF.frameMs)return;lastDraw=now;if(S.mode==='sonar'){drawSonar(now);drawCorr()}else if(S.mode==='doppler')drawDoppler();else if(S.mode==='ranging')drawRanging();else drawPosition()}
function activate(on){S.active=!!on;document.body.classList.toggle('acoustic-mode',S.active);$('acousticStage').hidden=!S.active;if(on){renderControls();renderStage();requestAnimationFrame(fit);$('selWave').value='off';$('selWave').dispatchEvent(new Event('change'))}else stopActivities()}function micStopped(){stopActivities();E.detach();if(S.active)live(false,'MIC OFF')}
E.on(m=>{if(m.type==='anchor-trigger'&&S.mode==='ranging'&&S.range.armed){$('apStatus').textContent='Poll terdeteksi · reply sample-accurate.';live(true,'REPLYING')}if(m.type==='anchor-rearmed'&&S.range.armed)live(true,'ANCHOR '+S.range.selected)});
let fitRAF=0;
function scheduleFit(){
  cancelAnimationFrame(fitRAF);
  fitRAF=requestAnimationFrame(()=>{fit();requestAnimationFrame(fit)});
}
window.addEventListener('resize',scheduleFit,{passive:true});
document.addEventListener('fullscreenchange',()=>{scheduleFit();setTimeout(scheduleFit,120)});
if(typeof ResizeObserver==='function'){
  const ro=new ResizeObserver(()=>scheduleFit());
  ro.observe($('acousticStage'));
}
setMode('sonar');window.SoundScopeAcoustic={activate,tick,micStopped,state:S,setMode};
})();
