/* PILAR SoundScope v4.3.1 — Acoustic Physics family. Stage 1: Echo Sonar */
(function(){
'use strict';
const A=window.SOUNDSCOPE_MORSE_AUDIO,C=window.PilarAcousticCore,E=window.PilarAcousticEngine,$=id=>document.getElementById(id);
if(!A||!C||!E||!$('acousticControlMount')||!$('acousticStage'))return;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),sleep=ms=>new Promise(r=>setTimeout(r,ms));
$('acousticControlMount').innerHTML=[
 '<div class="acp-family"><div class="acp-family-head"><span>ACOUSTIC PHYSICS</span><small>Echo · Motion · Ranging · Position</small></div><div class="acp-modes">',
 '<button class="btn on" data-ap-mode="sonar">📡 Echo Sonar</button><button class="btn" disabled>↔ Doppler <small>Stage 2</small></button>',
 '<button class="btn" disabled>📍 Multi-Anchor <small>Stage 3</small></button><button class="btn" disabled>◎ Position Radar <small>Stage 4</small></button></div></div>',
 '<div class="card"><b>📡 Echo Sonar v1</b><div class="hint">Kirim chirp pendek dari speaker bawaan. Mikrofon merekam bunyi langsung dan gema dalam satu sample clock; selisih waktunya dipakai untuk mengestimasi jarak pemantul.</div>',
 '<div class="acp-grid"><label>Suhu udara (°C)<input id="apTemp" type="number" min="-10" max="60" step="1" value="27"></label>',
 '<label>Jangkauan radar<select id="apRange"><option value="3">0–3 m</option><option value="5" selected>0–5 m</option><option value="8">0–8 m</option></select></label>',
 '<label>Baseline speaker↔mic (cm)<input id="apBase" type="number" min="0" max="300" step="1" value="0"></label>',
 '<label>Volume ping<select id="apVol"><option value=".20">Rendah</option><option value=".28" selected>Sedang</option><option value=".36">Agak kuat</option></select></label></div>',
 '<div class="acp-actions"><button class="btn good" id="apPing">◉ PING SONAR</button><button class="btn primary" id="apDemo">▶ Demo 2,0 m</button></div>',
 '<div class="acp-status" id="apStatus">Siap. Gunakan speaker bawaan; hindari Bluetooth karena latensinya tidak stabil.</div></div>',
 '<div class="card acp-readout"><b>HASIL</b><div><small>JARAK PEMANTUL</small><strong id="apDistance">—</strong></div><div><small>SELISIH WAKTU</small><strong id="apDt">—</strong></div><div><small>CEPAT RAMBAT</small><strong id="apC">—</strong></div><div><small>KUALITAS</small><strong id="apQ">—</strong></div></div>',
 '<div class="hint acp-safety"><b>Catatan:</b> radar ini mengukur <b>jarak saja</b>, bukan arah. Estimasi paling baik untuk permukaan besar dan keras. Volume dibatasi dan ping singkat; jangan dekatkan speaker ke telinga.</div>'
].join('');
$('acousticStage').innerHTML=[
 '<div class="acp-stage-head"><div><span class="acp-kicker">PILAR · ACOUSTIC INSTRUMENTATION PLATFORM</span><h2>Echo Sonar <em>range only</em></h2></div><span class="acp-live" id="apLive"><i></i><b id="apLiveText">READY</b></span></div>',
 '<div class="acp-chain"><span>PANCARKAN</span><i>→</i><span>RAMBAT</span><i>→</i><span>TERIMA</span><i>→</i><span>UKUR Δt</span><i>→</i><span>JARAK</span></div>',
 '<div class="acp-viz"><div class="acp-radar-wrap"><canvas id="apRadar"></canvas><div class="acp-overlay"><b id="apRadarValue">—</b><small>RANGE ONLY · ANGLE UNKNOWN</small></div></div>',
 '<div class="acp-corr-wrap"><div class="acp-cap">MATCHED FILTER · korelasi chirp vs waktu</div><canvas id="apCorr"></canvas></div></div>',
 '<div class="acp-aha" id="apAha">AHA: jarak berasal dari jeda antara bunyi langsung dan gema — bukan dari kuat-lemahnya suara.</div>'
].join('');
const radar=$('apRadar'),corr=$('apCorr'),rc=radar.getContext('2d'),cc=corr.getContext('2d'),S={active:false,busy:false,result:null,lastCorr:null,lastPing:0};
function fit(){for(const c of [radar,corr]){const r=c.getBoundingClientRect(),d=Math.min(1.6,devicePixelRatio||1);c.width=Math.max(10,Math.round(r.width*d));c.height=Math.max(10,Math.round(r.height*d));c._d=d}}
new ResizeObserver(fit).observe(radar);new ResizeObserver(fit).observe(corr);
function setStatus(s){$('apStatus').textContent=s}
function updateReadout(r){const t=+$('apTemp').value||27,c=C.speedOfSound(t);$('apC').textContent=c.toFixed(1)+' m/s';if(!r||!r.ok){$('apDistance').textContent='—';$('apDt').textContent='—';$('apQ').textContent='—';$('apRadarValue').textContent='—';return}$('apDistance').textContent=r.distanceM.toFixed(2)+' m';$('apDt').textContent=(r.dt*1000).toFixed(2)+' ms';$('apQ').textContent=Math.round(r.confidence*100)+'%';$('apRadarValue').textContent=r.distanceM.toFixed(2)+' m'}
function pingState(on,label){$('apLive').classList.toggle('on',on);$('apLiveText').textContent=label;$('apPing').disabled=on;S.busy=on}
function analyze(samples,chirp){const t=+$('apTemp').value||27,b=Math.max(0,(+$('apBase').value||0)/100),max=+$('apRange').value||5,r=C.analyzeEcho(samples,chirp,{sr:E.sr,tempC:t,baselineM:b,maxRangeM:max,minRangeM:.6,searchStartMs:20,searchEndMs:330});S.result=r;S.lastCorr=r.correlation||null;updateReadout(r);if(r.ok){setStatus('✓ Gema terdeteksi · direct '+r.direct.v.toFixed(2)+' · echo '+r.echo.v.toFixed(2)+'. Ulangi beberapa kali untuk melihat kestabilan.');$('apAha').textContent='AHA: Δt '+(r.dt*1000).toFixed(2)+' ms × '+r.c.toFixed(1)+' m/s menghasilkan lintasan tambahan '+r.excessM.toFixed(2)+' m.'}else{setStatus('Belum dapat jarak: '+r.reason+'. Coba permukaan keras, jarak 0,6–5 m, atau naikkan volume satu tingkat.');$('apAha').textContent='Belum ada dua puncak yang cukup jelas: SoundScope menolak menampilkan jarak daripada menebak.'}}
async function realPing(){if(S.busy)return;try{pingState(true,'ARMING');setStatus('Menyiapkan sample clock dan mikrofon…');await E.ensure();await sleep(90);const sr=E.sr,chirp=C.makeChirp({sr,durationMs:6,f0:2500,f1:6000,amp:.9}),mark=E.mark();S.lastPing=performance.now();await E.play(chirp,+$('apVol').value||.28,75);pingState(true,'PING');await sleep(390);const samples=E.slice(mark,E.mark());if(samples.length<sr*.18)throw Error('rekaman terlalu pendek');analyze(samples,chirp);pingState(false,S.result&&S.result.ok?'ECHO LOCK':'NO LOCK')}catch(e){pingState(false,'ERROR');setStatus('Sonar gagal: '+(e.message||String(e)))}}
function demo(){const sr=48000,chirp=C.makeChirp({sr,durationMs:6,f0:2500,f1:6000,amp:.9}),t=+$('apTemp').value||27,b=Math.max(0,(+$('apBase').value||0)/100),sim=C.synthEcho({sr,chirp,distanceM:2,tempC:t,baselineM:b,directDelayMs:70,directAmp:.72,echoAmp:.30,noise:.005,reflections:2});E.sr=sr;analyze(sim.samples,chirp);S.lastPing=performance.now();setStatus('DEMO sintetis 2,00 m · noise + pantulan tambahan. Gunakan PING SONAR untuk pengukuran nyata.');$('apLiveText').textContent='DEMO';$('apLive').classList.add('on');setTimeout(()=>$('apLive').classList.remove('on'),900)}
$('apPing').onclick=realPing;$('apDemo').onclick=demo;['apTemp','apRange','apBase'].forEach(id=>$(id).onchange=()=>updateReadout(S.result));
function drawRadar(now){const d=radar._d||1,W=radar.width/d,H=radar.height/d;rc.setTransform(d,0,0,d,0,0);rc.clearRect(0,0,W,H);const cx=W/2,cy=H*.56,R=Math.min(W,H)*.39,max=+$('apRange').value||5;rc.strokeStyle='rgba(126,238,255,.12)';rc.lineWidth=1;for(let i=1;i<=5;i++){rc.beginPath();rc.arc(cx,cy,R*i/5,0,Math.PI*2);rc.stroke();rc.fillStyle='rgba(157,178,202,.72)';rc.font='11px system-ui';rc.fillText((max*i/5).toFixed(i<5?1:0)+' m',cx+6,cy-R*i/5+13)}rc.strokeStyle='rgba(126,238,255,.10)';for(let a=0;a<8;a++){const q=a*Math.PI/4;rc.beginPath();rc.moveTo(cx,cy);rc.lineTo(cx+Math.cos(q)*R,cy+Math.sin(q)*R);rc.stroke()}rc.fillStyle='#63e3a0';rc.beginPath();rc.arc(cx,cy,6,0,7);rc.fill();rc.fillStyle='#9db2ca';rc.font='700 11px system-ui';rc.fillText('DEVICE',cx+10,cy+4);if(S.lastPing){const pr=((now-S.lastPing)%1300)/1300*R;rc.strokeStyle='rgba(105,186,255,'+(1-pr/R)*.55+')';rc.lineWidth=2;rc.beginPath();rc.arc(cx,cy,pr,0,7);rc.stroke()}if(S.result&&S.result.ok){const rr=clamp(S.result.distanceM/max,0,1)*R;rc.strokeStyle='#ffd36c';rc.lineWidth=4;rc.shadowColor='rgba(255,211,108,.45)';rc.shadowBlur=12;rc.beginPath();rc.arc(cx,cy,rr,0,7);rc.stroke();rc.shadowBlur=0}}
function drawCorr(){const d=corr._d||1,W=corr.width/d,H=corr.height/d;cc.setTransform(d,0,0,d,0,0);cc.clearRect(0,0,W,H);const pad=28;cc.strokeStyle='rgba(126,238,255,.10)';cc.lineWidth=1;for(let i=0;i<=5;i++){const y=pad+(H-2*pad)*i/5;cc.beginPath();cc.moveTo(pad,y);cc.lineTo(W-pad,y);cc.stroke()}const c=S.lastCorr;if(!c||!c.values.length){cc.fillStyle='#9db2ca';cc.font='14px system-ui';cc.fillText('Belum ada ping. Jalankan demo atau PING SONAR.',pad,H/2);return}const a=c.values,step=Math.max(1,Math.floor(a.length/Math.max(1,W-2*pad)));cc.beginPath();cc.strokeStyle='#69baff';cc.lineWidth=2;for(let x=0;x<W-2*pad;x++){let m=0,s=x*step;for(let j=0;j<step&&s+j<a.length;j++)m=Math.max(m,a[s+j]);const y=H-pad-m*(H-2*pad);if(x===0)cc.moveTo(pad+x,y);else cc.lineTo(pad+x,y)}cc.stroke();if(S.result&&S.result.direct){for(const p of [{q:S.result.direct,label:'DIRECT',col:'#63e3a0'},{q:S.result.echo,label:'ECHO',col:'#ffd36c'}]){if(!p.q)continue;const rel=(p.q.i-c.offset)/Math.max(1,a.length-1),x=pad+clamp(rel,0,1)*(W-2*pad);cc.strokeStyle=p.col;cc.setLineDash([4,4]);cc.beginPath();cc.moveTo(x,pad);cc.lineTo(x,H-pad);cc.stroke();cc.setLineDash([]);cc.fillStyle=p.col;cc.font='700 11px system-ui';cc.fillText(p.label,x+4,pad+12)}}}
function tick(now){if(S.active){drawRadar(now);drawCorr()}}
function activate(on){S.active=!!on;document.body.classList.toggle('acoustic-mode',S.active);$('acousticStage').hidden=!S.active;if(on){fit();updateReadout(S.result);$('selWave').value='off';$('selWave').dispatchEvent(new Event('change'))}}
function micStopped(){E.detach();if(S.active){pingState(false,'MIC OFF');setStatus('Mikrofon dihentikan. Tekan PING SONAR untuk mengaktifkannya kembali.')}}
window.SoundScopeAcoustic={activate,tick,micStopped,realPing,demo,state:S};
})();
