/* PILAR SoundScope v4.4.0 — Acoustic Physics */
(function(){
'use strict';
const A=window.SOUNDSCOPE_MORSE_AUDIO,C=window.PilarAcousticCore,E=window.PilarAcousticEngine,$=id=>document.getElementById(id);
if(!A||!C||!E||!$('acousticControlMount')||!$('acousticStage'))return;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const DEF=[{id:'A',x:0,y:0,poll:1000,reply:1800},{id:'B',x:6,y:0,poll:1200,reply:2000},{id:'C',x:6,y:4,poll:1400,reply:2200},{id:'D',x:0,y:4,poll:1600,reply:2400}];
let cached=null;try{cached=JSON.parse(localStorage.getItem('ss_acoustic_anchors_v1')||'null')}catch(_){}
const anchors=DEF.map((a,i)=>({...a,x:cached?.[i]?.x??a.x,y:cached?.[i]?.y??a.y,range:cached?.[i]?.range??null,bias:cached?.[i]?.bias??0,q:cached?.[i]?.q??0}));
const S={active:false,mode:'sonar',busy:false,sonar:null,corr:null,lastPing:0,dop:{tx:false,tracking:false,baseline:2000,obs:0,vel:0,snr:0,history:[],last:0},range:{selected:'A',turn:120,armed:false,last:null},pos:null,anchors};
function save(){try{localStorage.setItem('ss_acoustic_anchors_v1',JSON.stringify(anchors.map(a=>({id:a.id,x:a.x,y:a.y,range:a.range,bias:a.bias,q:a.q}))))}catch(_){}}
$('acousticControlMount').innerHTML='<div class="acp-family"><div class="acp-family-head"><span>ACOUSTIC PHYSICS</span><small>Echo · Motion · Ranging · Position</small></div><div class="acp-modes">'+[['sonar','📡 Echo Sonar'],['doppler','↔ Doppler'],['ranging','📍 Multi-Anchor'],['position','◎ Position Radar']].map(([m,l])=>'<button class="btn" data-ap-mode="'+m+'">'+l+'</button>').join('')+'</div></div><div id="acpControls"></div>';
$('acousticStage').innerHTML='<div class="acp-stage-head"><div><span class="acp-kicker">PILAR · ACOUSTIC INSTRUMENTATION PLATFORM</span><h2 id="apTitle">—</h2></div><span class="acp-live" id="apLive"><i></i><b id="apLiveText">READY</b></span></div><div class="acp-chain" id="apChain"></div><div class="acp-stage-body" id="apBody"></div><div class="acp-aha" id="apAha"></div>';
function live(on,label){$('apLive').classList.toggle('on',!!on);$('apLiveText').textContent=label}function chain(items){$('apChain').innerHTML=items.map((x,i)=>'<span>'+x+'</span>'+(i<items.length-1?'<i>→</i>':'')).join('')}
function stopActivities(){S.dop.tracking=false;if(S.dop.tx){E.stopTone();S.dop.tx=false}if(S.range.armed){E.stopResponder();S.range.armed=false}live(false,'READY')}
function setMode(m){stopActivities();S.mode=m;document.querySelectorAll('[data-ap-mode]').forEach(b=>b.classList.toggle('on',b.dataset.apMode===m));renderControls();renderStage();requestAnimationFrame(fit)}
document.querySelectorAll('[data-ap-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.apMode));const temp=()=>+($('apTemp')?.value||27);
function renderControls(){const el=$('acpControls');
 if(S.mode==='sonar')el.innerHTML='<div class="card"><b>📡 Echo Sonar</b><div class="hint">Bunyi langsung dan gema direkam pada sample clock yang sama. Mode v1 aman mulai sekitar 0,6 m.</div><div class="acp-grid"><label>Suhu (°C)<input id="apTemp" type="number" value="27"></label><label>Range<select id="apRange"><option value="3">0–3 m</option><option value="5" selected>0–5 m</option><option value="8">0–8 m</option></select></label><label>Baseline speaker↔mic (cm)<input id="apBase" type="number" value="0"></label><label>Volume<select id="apVol"><option value=".20">Rendah</option><option value=".28" selected>Sedang</option><option value=".36">Agak kuat</option></select></label></div><div class="acp-actions"><button class="btn good" id="apPing">◉ PING SONAR</button><button class="btn primary" id="apDemo">▶ Demo 2,0 m</button></div><div class="acp-status" id="apStatus">Gunakan speaker bawaan; hindari Bluetooth.</div></div><div class="card acp-readout"><b>HASIL</b><div><small>JARAK</small><strong id="apDistance">—</strong></div><div><small>Δt</small><strong id="apDt">—</strong></div><div><small>c</small><strong id="apC">—</strong></div><div><small>KUALITAS</small><strong id="apQ">—</strong></div></div>';
 else if(S.mode==='doppler')el.innerHTML='<div class="card"><b>↔ Doppler Lab</b><div class="hint">Dua perangkat: HP sebagai TX, IFP sebagai RX. Kalibrasi diam menghapus offset oscillator/sample-clock.</div><div class="acp-grid"><label>Carrier<select id="dpFreq"><option>1500</option><option selected>2000</option><option>2500</option><option>3000</option></select></label><label>Suhu (°C)<input id="apTemp" type="number" value="27"></label></div><div class="acp-actions quad"><button class="btn good" id="dpTx">▶ TX NADA</button><button class="btn danger" id="dpStop">■ Stop TX</button><button class="btn primary" id="dpCal">◎ Kalibrasi diam</button><button class="btn good" id="dpTrack">↔ Mulai tracking</button></div><div class="acp-status" id="apStatus">RX: diamkan sumber lalu tekan Kalibrasi.</div></div><div class="card acp-readout"><b>DOPPLER</b><div><small>BASELINE</small><strong id="dpBase">—</strong></div><div><small>TERIMA</small><strong id="dpObs">—</strong></div><div><small>Δf</small><strong id="dpShift">—</strong></div><div><small>KECEPATAN</small><strong id="dpVel">—</strong></div></div>';
 else if(S.mode==='ranging')el.innerHTML='<div class="card"><b>📍 Multi-Anchor Ranging</b><div class="hint">HP Anchor membalas poll otomatis setelah 120 ms di AudioWorklet. Tiap anchor mempunyai pasangan frekuensi unik.</div><div class="acp-grid"><label>Anchor<select id="rgId">'+anchors.map(a=>'<option>'+a.id+'</option>').join('')+'</select></label><label>Suhu (°C)<input id="apTemp" type="number" value="27"></label><label>Jarak kalibrasi (m)<input id="rgRef" type="number" value="1" step=".1"></label></div><div class="acp-actions quad"><button class="btn good" id="rgArm">📡 ARM ANCHOR</button><button class="btn primary" id="rgOne">◎ Ukur terpilih</button><button class="btn primary" id="rgAll">◎ Ukur semua</button><button class="btn warn" id="rgCal">⚙ Kalibrasi</button></div><div class="acp-status" id="apStatus">Di HP pilih ID lalu ARM. Di IFP tekan Ukur.</div></div><div class="card"><b>ANCHOR TABLE</b><div class="anchor-table" id="rgTable"></div></div>';
 else el.innerHTML='<div class="card"><b>◎ Position Radar</b><div class="hint">Gabungkan minimal tiga range. Solver least-squares menampilkan posisi dan residual tiap anchor.</div><div class="acp-actions"><button class="btn good" id="psSolve">◎ Hitung posisi</button><button class="btn primary" id="psDemo">▶ Demo target</button></div><div class="acp-status" id="apStatus">Range dari Multi-Anchor otomatis dibawa ke sini.</div></div><div class="card"><b>KOORDINAT & RANGE</b><div class="anchor-table" id="psTable"></div></div>';
 bindControls()}
function renderRangeTable(){const t=$('rgTable');if(t)t.innerHTML=anchors.map(a=>'<div class="anchor-row simple"><b>'+a.id+'</b><span>'+a.poll+'→'+a.reply+' Hz</span><span>'+(a.range==null?'—':a.range.toFixed(2)+' m')+'</span><span>bias '+a.bias.toFixed(2)+' m</span></div>').join('')}
function renderPositionTable(){const t=$('psTable');if(!t)return;t.innerHTML=anchors.map(a=>'<div class="anchor-row"><b>'+a.id+'</b><label>X<input data-a="'+a.id+'" data-k="x" type="number" step=".1" value="'+a.x+'"></label><label>Y<input data-a="'+a.id+'" data-k="y" type="number" step=".1" value="'+a.y+'"></label><label>Range<input data-a="'+a.id+'" data-k="range" type="number" step=".01" value="'+(a.range??'')+'" placeholder="—"></label><span class="anchor-q">'+(a.range==null?'—':a.range.toFixed(2)+' m')+'</span></div>').join('');t.querySelectorAll('input[data-a]').forEach(i=>i.onchange=()=>{const a=anchors.find(x=>x.id===i.dataset.a),v=parseFloat(i.value),k=i.dataset.k;a[k]=Number.isFinite(v)?v:(k==='range'?null:a[k]);save();solvePosition(false)})}
function bindControls(){if(S.mode==='sonar'){$('apPing').onclick=sonarPing;$('apDemo').onclick=sonarDemo}if(S.mode==='doppler'){$('dpTx').onclick=dopplerTx;$('dpStop').onclick=()=>{E.stopTone();S.dop.tx=false;live(false,'TX OFF')};$('dpCal').onclick=dopplerCalibrate;$('dpTrack').onclick=()=>{S.dop.tracking=!S.dop.tracking;$('dpTrack').textContent=S.dop.tracking?'■ Stop tracking':'↔ Mulai tracking';live(S.dop.tracking,S.dop.tracking?'TRACKING':'READY')}}if(S.mode==='ranging'){$('rgId').value=S.range.selected;$('rgId').onchange=e=>S.range.selected=e.target.value;$('rgArm').onclick=armAnchor;$('rgOne').onclick=()=>measureAnchor(S.range.selected,false);$('rgAll').onclick=measureAll;$('rgCal').onclick=calibrateAnchor;renderRangeTable()}if(S.mode==='position'){$('psSolve').onclick=()=>solvePosition(true);$('psDemo').onclick=positionDemo;renderPositionTable()}}
function renderStage(){const body=$('apBody');if(S.mode==='sonar'){$('apTitle').innerHTML='Echo Sonar <em>range only</em>';chain(['PANCARKAN','RAMBAT','TERIMA','UKUR Δt','JARAK']);body.innerHTML='<div class="acp-viz"><div class="acp-radar-wrap"><canvas id="apMain"></canvas><div class="acp-overlay"><b id="apHero">—</b><small>RANGE ONLY · ANGLE UNKNOWN</small></div></div><div class="acp-corr-wrap"><div class="acp-cap">MATCHED FILTER · DIRECT vs ECHO</div><canvas id="apAux"></canvas></div></div>';$('apAha').textContent='AHA: jarak berasal dari jeda bunyi langsung dan gema.'}else if(S.mode==='doppler'){$('apTitle').innerHTML='Doppler Lab <em>motion from Δf</em>';chain(['NADA ACUAN','GERAK','Δf','HITUNG v','ARAH']);body.innerHTML='<div class="acp-viz"><div class="acp-radar-wrap"><canvas id="apMain"></canvas><div class="acp-overlay"><b id="apHero">0.00 m/s</b><small>+ MENDEKAT · − MENJAUH</small></div></div><div class="acp-corr-wrap"><div class="acp-cap">FREQUENCY TRACE · Hz vs waktu</div><canvas id="apAux"></canvas></div></div>';$('apAha').textContent='AHA: gerak muncul sebagai pergeseran frekuensi beberapa hertz.'}else if(S.mode==='ranging'){$('apTitle').innerHTML='Multi-Anchor Ranging <em>two-way acoustic</em>';chain(['POLL','ANCHOR','DELAY TETAP','REPLY','RANGE']);body.innerHTML='<div class="acp-viz one"><div class="acp-corr-wrap"><div class="acp-cap">PAIRWISE TIMING</div><canvas id="apMain"></canvas></div><div class="anchor-stage" id="apAnchorStage"></div></div>';$('apAha').textContent='AHA: round-trip diukur pada satu sample clock; jam antardevice tidak perlu sinkron.'}else{$('apTitle').innerHTML='Position Radar <em>multilateration 2D</em>';chain(['RANGE A–D','LINGKARAN','SOLVER','RESIDUAL','POSISI']);body.innerHTML='<div class="acp-viz"><div class="acp-radar-wrap"><canvas id="apMain"></canvas><div class="acp-overlay"><b id="apHero">—</b><small>MULTI-ANCHOR POSITION</small></div></div><div class="acp-corr-wrap"><div class="acp-cap">RESIDUAL · model − measured</div><canvas id="apAux"></canvas></div></div>';$('apAha').textContent='AHA: posisi adalah titik yang paling konsisten dengan beberapa jarak.'}}
let main,aux,mc,xc;function fit(){main=$('apMain');aux=$('apAux');for(const c of [main,aux].filter(Boolean)){const r=c.getBoundingClientRect(),d=Math.min(1.6,devicePixelRatio||1);c.width=Math.max(10,Math.round(r.width*d));c.height=Math.max(10,Math.round(r.height*d));c._d=d}mc=main?.getContext('2d')||null;xc=aux?.getContext('2d')||null}
async function sonarPing(){if(S.busy)return;S.busy=true;live(true,'PING');try{await E.ensure();await sleep(90);const chirp=C.makeChirp({sr:E.sr,durationMs:6,f0:2500,f1:6000,amp:.9}),mark=E.mark();S.lastPing=performance.now();await E.playSamples(chirp,+$('apVol').value||.28,75);await sleep(390);const x=E.slice(mark,E.mark()),r=C.analyzeEcho(x,chirp,{sr:E.sr,tempC:temp(),baselineM:Math.max(0,(+$('apBase').value||0)/100),maxRangeM:+$('apRange').value||5,minRangeM:.6,searchStartMs:20,searchEndMs:330});S.sonar=r;S.corr=r.correlation;updateSonar(r);$('apStatus').textContent=r.ok?'✓ '+r.distanceM.toFixed(2)+' m':'Belum dapat jarak: '+r.reason;live(false,r.ok?'ECHO LOCK':'NO LOCK')}catch(e){$('apStatus').textContent='Sonar gagal: '+(e.message||e);live(false,'ERROR')}finally{S.busy=false}}
function sonarDemo(){const chirp=C.makeChirp({sr:48000,durationMs:6}),sim=C.synthEcho({sr:48000,chirp,distanceM:2,tempC:27,noise:.006,echoAmp:.28,reflections:2}),r=C.analyzeEcho(sim.samples,chirp,{sr:48000,tempC:27,maxRangeM:5,minRangeM:.6});S.sonar=r;S.corr=r.correlation;S.lastPing=performance.now();updateSonar(r);$('apStatus').textContent='Demo sintetis 2,00 m.'}function updateSonar(r){if(!$('apC'))return;$('apC').textContent=C.speedOfSound(temp()).toFixed(1)+' m/s';if(!r?.ok)return;$('apDistance').textContent=r.distanceM.toFixed(2)+' m';$('apDt').textContent=(r.dt*1000).toFixed(2)+' ms';$('apQ').textContent=Math.round(r.confidence*100)+'%';if($('apHero'))$('apHero').textContent=r.distanceM.toFixed(2)+' m'}
function dopplerTx(){const f=+$('dpFreq').value||2000;S.dop.tracking=false;E.startTone(f,.14);S.dop.tx=true;live(true,'TX '+f+' Hz');$('apStatus').textContent='TX aktif. Gunakan volume sedang dan gerak lurus.'}async function dopplerSample(){await E.ensure();const x=E.recent(140);if(x.length<E.sr*.08)return null;return C.estimateTone(x,{sr:E.sr,center:+$('dpFreq').value||2000,span:45,step:1,minSnrDb:5})}
async function dopplerCalibrate(){try{E.stopTone();S.dop.tx=false;live(true,'CALIBRATING');await E.ensure();await sleep(300);const vals=[];for(let i=0;i<10;i++){const r=await dopplerSample();if(r?.ok)vals.push(r.freq);await sleep(110)}if(vals.length<5)throw Error('carrier belum cukup jelas');S.dop.baseline=vals.reduce((a,b)=>a+b,0)/vals.length;$('dpBase').textContent=S.dop.baseline.toFixed(2)+' Hz';$('apStatus').textContent='Kalibrasi selesai. Mulai tracking.';live(false,'CAL OK')}catch(e){$('apStatus').textContent='Kalibrasi gagal: '+(e.message||e);live(false,'NO LOCK')}}
async function dopplerTick(now){if(!S.dop.tracking||now-S.dop.last<120)return;S.dop.last=now;const r=await dopplerSample();if(!r?.ok)return;const d=C.dopplerVelocity(r.freq,S.dop.baseline,temp());S.dop.obs=r.freq;S.dop.vel=.72*S.dop.vel+.28*d.velocity;S.dop.snr=r.snrDb;S.dop.history.push({t:now,f:r.freq,v:S.dop.vel});while(S.dop.history.length>90)S.dop.history.shift();if($('dpObs')){$('dpBase').textContent=S.dop.baseline.toFixed(2)+' Hz';$('dpObs').textContent=r.freq.toFixed(2)+' Hz';$('dpShift').textContent=(r.freq-S.dop.baseline>=0?'+':'')+(r.freq-S.dop.baseline).toFixed(2)+' Hz';$('dpVel').textContent=(S.dop.vel>=0?'+':'')+S.dop.vel.toFixed(2)+' m/s';$('apStatus').textContent=r.snrDb.toFixed(0)+' dB · '+(S.dop.vel>.15?'mendekat':S.dop.vel<-.15?'menjauh':'hampir diam')}}
const selected=()=>anchors.find(a=>a.id===S.range.selected)||anchors[0];async function armAnchor(){try{const a=selected();if(S.range.armed){E.stopResponder();S.range.armed=false;$('rgArm').textContent='📡 ARM ANCHOR';live(false,'ANCHOR OFF');return}await E.setResponder({pollFreq:a.poll,replyFreq:a.reply,delayMs:S.range.turn,replyMs:24,amp:.26,minAmp:.006});S.range.armed=true;$('rgArm').textContent='■ STOP ANCHOR';$('apStatus').textContent='Anchor '+a.id+' armed: '+a.poll+' → '+a.reply+' Hz.';live(true,'ANCHOR '+a.id)}catch(e){$('apStatus').textContent='Gagal arm: '+(e.message||e)}}
async function rawRange(a){await E.ensure();E.stopResponder();await sleep(80);const mark=E.mark();await E.playToneBurst(a.poll,24,.24,75);await sleep(500);const x=E.slice(mark,E.mark()),p=C.detectToneOnset(x,{sr:E.sr,freq:a.poll,winMs:7,hopMs:1,ratio:.45,consecutive:2}),q=C.detectToneOnset(x,{sr:E.sr,freq:a.reply,winMs:7,hopMs:1,ratio:.45,consecutive:2});if(!p.ok||!q.ok||q.index<=p.index)throw Error('poll/reply belum terdeteksi');const dt=(q.index-p.index)/E.sr,rr=C.rangeFromRoundTrip(dt,S.range.turn,temp(),0);return {rawM:rr.rawM,dt,poll:p,reply:q}}
async function measureAnchor(id,calOnly){if(S.busy)return null;S.busy=true;const a=anchors.find(x=>x.id===id);S.range.selected=id;live(true,'RANGE '+id);try{const r=await rawRange(a);if(!calOnly){a.range=Math.max(0,r.rawM-a.bias);a.q=Math.min(r.poll.confidence,r.reply.confidence);S.range.last={id,...r,distance:a.range};save();renderRangeTable();renderAnchorStage();$('apStatus').textContent='✓ '+id+' = '+a.range.toFixed(2)+' m'}live(false,'RANGE OK');return r}catch(e){$('apStatus').textContent=id+' gagal: '+(e.message||e);live(false,'NO REPLY');return null}finally{S.busy=false}}
async function measureAll(){for(const a of anchors){S.range.selected=a.id;if($('rgId'))$('rgId').value=a.id;await measureAnchor(a.id,false);await sleep(220)}}async function calibrateAnchor(){const a=selected(),ref=Math.max(.5,+$('rgRef').value||1),r=await measureAnchor(a.id,true);if(r){a.bias=r.rawM-ref;save();renderRangeTable();$('apStatus').textContent='✓ bias '+a.id+' = '+a.bias.toFixed(2)+' m'}}
function renderAnchorStage(){const el=$('apAnchorStage');if(el)el.innerHTML=anchors.map(a=>'<div class="anchor-tile '+(a.range!=null?'ok':'')+'"><b>'+a.id+'</b><span>'+(a.range==null?'WAIT':a.range.toFixed(2)+' m')+'</span><small>'+a.poll+'→'+a.reply+' Hz</small></div>').join('')}
function solvePosition(show){const pts=anchors.filter(a=>a.range!=null).map(a=>({id:a.id,x:+a.x,y:+a.y,r:+a.range,w:a.q?(.4+.6*a.q):1})),r=C.trilaterate(pts);S.pos=r;if(show&&$('apStatus'))$('apStatus').textContent=r.ok?'✓ Posisi '+r.x.toFixed(2)+', '+r.y.toFixed(2)+' m · RMS '+r.rms.toFixed(2)+' m':'Belum bisa: '+r.reason;if($('apHero'))$('apHero').textContent=r.ok?r.x.toFixed(2)+', '+r.y.toFixed(2)+' m':'—';return r}function positionDemo(){const tx=2.4,ty=1.7;anchors.forEach((a,i)=>{a.range=Math.hypot(tx-a.x,ty-a.y)+[.01,-.02,.03,-.015][i];a.q=.9});save();renderPositionTable();solvePosition(true);$('apStatus').textContent+=' · target demo 2,40 × 1,70 m.'}
function drawGrid(ctx,W,H){ctx.strokeStyle='rgba(126,238,255,.1)';for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(0,H*i/5);ctx.lineTo(W,H*i/5);ctx.stroke()}}
function drawSonar(now){if(!mc)return;const d=main._d||1,W=main.width/d,H=main.height/d,cx=W/2,cy=H*.56,R=Math.min(W,H)*.39,max=+$('apRange')?.value||5;mc.setTransform(d,0,0,d,0,0);mc.clearRect(0,0,W,H);for(let i=1;i<=5;i++){mc.strokeStyle='rgba(126,238,255,.12)';mc.beginPath();mc.arc(cx,cy,R*i/5,0,7);mc.stroke()}mc.fillStyle='#63e3a0';mc.beginPath();mc.arc(cx,cy,6,0,7);mc.fill();if(S.lastPing){const pr=((now-S.lastPing)%1300)/1300*R;mc.strokeStyle='rgba(105,186,255,.45)';mc.beginPath();mc.arc(cx,cy,pr,0,7);mc.stroke()}if(S.sonar?.ok){mc.strokeStyle='#ffd36c';mc.lineWidth=4;mc.beginPath();mc.arc(cx,cy,clamp(S.sonar.distanceM/max,0,1)*R,0,7);mc.stroke()}}
function drawCorr(){if(!xc)return;const d=aux._d||1,W=aux.width/d,H=aux.height/d;xc.setTransform(d,0,0,d,0,0);xc.clearRect(0,0,W,H);drawGrid(xc,W,H);const c=S.corr;if(!c?.values?.length)return;const a=c.values,pad=24,step=Math.max(1,Math.floor(a.length/Math.max(1,W-2*pad)));xc.strokeStyle='#69baff';xc.lineWidth=2;xc.beginPath();for(let x=0;x<W-2*pad;x++){let m=0;for(let j=0;j<step&&x*step+j<a.length;j++)m=Math.max(m,a[x*step+j]);const y=H-pad-m*(H-2*pad);x?xc.lineTo(pad+x,y):xc.moveTo(pad+x,y)}xc.stroke()}
function drawDoppler(){if(!mc||!xc)return;let d=main._d||1,W=main.width/d,H=main.height/d,cx=W/2,cy=H*.58,r=Math.min(W,H)*.31,v=clamp(S.dop.vel,-3,3),ang=-Math.PI*.75+(v+3)/6*Math.PI*1.5;mc.setTransform(d,0,0,d,0,0);mc.clearRect(0,0,W,H);mc.strokeStyle='rgba(126,238,255,.18)';mc.lineWidth=14;mc.beginPath();mc.arc(cx,cy,r,Math.PI*.25,Math.PI*.75,true);mc.stroke();mc.strokeStyle=v>.15?'#63e3a0':v<-.15?'#69baff':'#ffd36c';mc.lineWidth=5;mc.beginPath();mc.moveTo(cx,cy);mc.lineTo(cx+Math.cos(ang)*r*.85,cy+Math.sin(ang)*r*.85);mc.stroke();if($('apHero'))$('apHero').textContent=(v>=0?'+':'')+v.toFixed(2)+' m/s';d=aux._d||1;W=aux.width/d;H=aux.height/d;xc.setTransform(d,0,0,d,0,0);xc.clearRect(0,0,W,H);drawGrid(xc,W,H);const h=S.dop.history;if(h.length<2)return;const f0=S.dop.baseline||2000,span=18;xc.strokeStyle='#7eeeff';xc.lineWidth=2;xc.beginPath();h.forEach((p,i)=>{const x=20+i/Math.max(1,h.length-1)*(W-40),y=H/2-(p.f-f0)/span*(H*.42);i?xc.lineTo(x,y):xc.moveTo(x,y)});xc.stroke()}
function drawRanging(){if(!mc)return;const d=main._d||1,W=main.width/d,H=main.height/d,y=H/2;mc.setTransform(d,0,0,d,0,0);mc.clearRect(0,0,W,H);mc.strokeStyle='rgba(126,238,255,.2)';mc.beginPath();mc.moveTo(30,y);mc.lineTo(W-30,y);mc.stroke();const r=S.range.last;if(!r)return;const total=Math.max(.2,r.dt),x0=60,x1=W-60,scale=(x1-x0)/total;[{t:0,l:'POLL',c:'#63e3a0'},{t:S.range.turn/1000,l:'DELAY',c:'#ffd36c'},{t:r.dt,l:'REPLY',c:'#69baff'}].forEach(e=>{const x=x0+e.t*scale;mc.strokeStyle=e.c;mc.beginPath();mc.moveTo(x,y-55);mc.lineTo(x,y+55);mc.stroke();mc.fillStyle=e.c;mc.fillText(e.l,x+4,y-35)})}
function drawPosition(){if(!mc||!xc)return;const d=main._d||1,W=main.width/d,H=main.height/d,maxX=Math.max(1,...anchors.map(a=>a.x)),maxY=Math.max(1,...anchors.map(a=>a.y)),pad=36,s=Math.min((W-2*pad)/maxX,(H-2*pad)/maxY),tx=x=>pad+x*s,ty=y=>H-pad-y*s;mc.setTransform(d,0,0,d,0,0);mc.clearRect(0,0,W,H);mc.strokeStyle='rgba(126,238,255,.16)';mc.strokeRect(pad,H-pad-maxY*s,maxX*s,maxY*s);anchors.forEach(a=>{const x=tx(a.x),y=ty(a.y);if(a.range!=null){mc.strokeStyle='rgba(105,186,255,.22)';mc.beginPath();mc.arc(x,y,a.range*s,0,7);mc.stroke()}mc.fillStyle='#63e3a0';mc.beginPath();mc.arc(x,y,7,0,7);mc.fill();mc.fillStyle='#eef7ff';mc.fillText(a.id,x+10,y-8)});const r=S.pos||solvePosition(false);if(r?.ok){const x=tx(r.x),y=ty(r.y);mc.fillStyle='#ffd36c';mc.beginPath();mc.arc(x,y,8,0,7);mc.fill();mc.strokeStyle='rgba(255,211,108,.45)';mc.beginPath();mc.arc(x,y,Math.max(5,r.uncertainty*s),0,7);mc.stroke()}const d2=aux._d||1,W2=aux.width/d2,H2=aux.height/d2;xc.setTransform(d2,0,0,d2,0,0);xc.clearRect(0,0,W2,H2);if(!r?.ok)return;const mr=Math.max(.1,...r.residuals.map(z=>Math.abs(z.residual))),bw=(W2-60)/r.residuals.length;r.residuals.forEach((z,i)=>{const x=35+i*bw+bw*.15,h=z.residual/mr*(H2*.35);xc.fillStyle=z.residual>=0?'#ff6d83':'#69baff';xc.fillRect(x,h>=0?H2/2-h:H2/2,bw*.7,Math.abs(h));xc.fillStyle='#eef7ff';xc.fillText(z.id,x+bw*.25,H2-10)})}
function tick(now){if(!S.active)return;if(S.mode==='doppler')dopplerTick(now);if(S.mode==='sonar'){drawSonar(now);drawCorr()}else if(S.mode==='doppler')drawDoppler();else if(S.mode==='ranging')drawRanging();else drawPosition()}
function activate(on){S.active=!!on;document.body.classList.toggle('acoustic-mode',S.active);$('acousticStage').hidden=!S.active;if(on){renderControls();renderStage();requestAnimationFrame(fit);$('selWave').value='off';$('selWave').dispatchEvent(new Event('change'))}else stopActivities()}function micStopped(){stopActivities();E.detach();if(S.active)live(false,'MIC OFF')}
E.on(m=>{if(m.type==='anchor-trigger'&&S.mode==='ranging'&&S.range.armed){$('apStatus').textContent='Poll terdeteksi · reply sample-accurate.';live(true,'REPLYING')}if(m.type==='anchor-rearmed'&&S.range.armed)live(true,'ANCHOR '+S.range.selected)});
setMode('sonar');window.SoundScopeAcoustic={activate,tick,micStopped,state:S,setMode};
})();