-- PILAR Pulse v0.1
-- Run once in Supabase SQL Editor.
-- Privacy model: Supabase anonymous auth per browser; no fingerprinting, no precise location.

create extension if not exists pgcrypto;

create table if not exists public.pilar_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  public_id text not null unique,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  current_app text not null default 'hub',
  device_class text,
  browser text,
  platform text,
  viewport text,
  touch_points integer not null default 0,
  webgl boolean not null default false,
  webgpu boolean not null default false,
  pulse_enabled boolean not null default true
);

create table if not exists public.pilar_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  started_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  current_app text not null default 'hub',
  page_path text
);

create index if not exists pilar_sessions_user_idx on public.pilar_sessions(user_id, last_seen desc);

create table if not exists public.pilar_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid references public.pilar_sessions(id) on delete set null,
  app_id text not null,
  event_name text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists pilar_events_user_idx on public.pilar_events(user_id, created_at desc);

create table if not exists public.pilar_messages (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null references auth.users(id) on delete cascade,
  sender text not null check (sender in ('visitor','developer')),
  body text not null check (char_length(body) between 1 and 1200),
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists pilar_messages_visitor_idx on public.pilar_messages(visitor_id, created_at);

create or replace function public.pilar_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select lower(coalesce(auth.jwt()->>'email','')) = 'rizalabdurrahman05@guru.smp.belajar.id';
$$;

revoke all on function public.pilar_is_admin() from public;
grant execute on function public.pilar_is_admin() to authenticated;

alter table public.pilar_profiles enable row level security;
alter table public.pilar_sessions enable row level security;
alter table public.pilar_events enable row level security;
alter table public.pilar_messages enable row level security;

drop policy if exists "pulse profiles read" on public.pilar_profiles;
create policy "pulse profiles read" on public.pilar_profiles
for select to authenticated
using (auth.uid() = user_id or public.pilar_is_admin());

drop policy if exists "pulse profiles insert" on public.pilar_profiles;
create policy "pulse profiles insert" on public.pilar_profiles
for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "pulse profiles update" on public.pilar_profiles;
create policy "pulse profiles update" on public.pilar_profiles
for update to authenticated
using (auth.uid() = user_id or public.pilar_is_admin())
with check (auth.uid() = user_id or public.pilar_is_admin());

drop policy if exists "pulse sessions read" on public.pilar_sessions;
create policy "pulse sessions read" on public.pilar_sessions
for select to authenticated
using (auth.uid() = user_id or public.pilar_is_admin());

drop policy if exists "pulse sessions insert" on public.pilar_sessions;
create policy "pulse sessions insert" on public.pilar_sessions
for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "pulse sessions update" on public.pilar_sessions;
create policy "pulse sessions update" on public.pilar_sessions
for update to authenticated
using (auth.uid() = user_id or public.pilar_is_admin())
with check (auth.uid() = user_id or public.pilar_is_admin());

drop policy if exists "pulse events insert" on public.pilar_events;
create policy "pulse events insert" on public.pilar_events
for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "pulse events admin read" on public.pilar_events;
create policy "pulse events admin read" on public.pilar_events
for select to authenticated
using (public.pilar_is_admin());

drop policy if exists "pulse messages read" on public.pilar_messages;
create policy "pulse messages read" on public.pilar_messages
for select to authenticated
using (auth.uid() = visitor_id or public.pilar_is_admin());

drop policy if exists "pulse messages insert" on public.pilar_messages;
create policy "pulse messages insert" on public.pilar_messages
for insert to authenticated
with check (
  (auth.uid() = visitor_id and sender = 'visitor')
  or (public.pilar_is_admin() and sender = 'developer')
);

drop policy if exists "pulse messages admin update" on public.pilar_messages;
create policy "pulse messages admin update" on public.pilar_messages
for update to authenticated
using (public.pilar_is_admin())
with check (public.pilar_is_admin());

grant select, insert, update on public.pilar_profiles to authenticated;
grant select, insert, update on public.pilar_sessions to authenticated;
grant select, insert on public.pilar_events to authenticated;
grant select, insert, update on public.pilar_messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Realtime for developer dashboard + user chat.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='pilar_profiles'
  ) then
    alter publication supabase_realtime add table public.pilar_profiles;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='pilar_messages'
  ) then
    alter publication supabase_realtime add table public.pilar_messages;
  end if;
end $$;
